### ISSUE TITLE
user/group create should use vars

### ISSUE THREAD

**Issue by warmans** [William-Yeh/ansible-prometheus#15]
Surely this is wrong: 

main.yml

```
- name: create Prometheus group
  group: name=prometheus state=present

- name: create Prometheus user
  user:
    name: prometheus
    group: prometheus
    createhome: no
    shell: /sbin/nologin
    comment: "Prometheus User"
    state: present
```

should be:

```
- name: create Prometheus group
  group: name="{{ prometheus_group }}" state=present

- name: create Prometheus user
  user:
    name: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    createhome: no
    shell: /sbin/nologin
    comment: "Prometheus User"
    state: present
```
